### ISSUE TITLE
生成图片太模糊了

### ISSUE THREAD

**Issue by lrjxgl** [zhengyima/DeepNude_NoWatermark_withModel#1]
生成图片太模糊了，这个怎么设置？

**Comment by zhengyima** [comment]
模型就这样= =等晚上有空研究一下

**Comment by graycrown** [comment]
太假了，网上吹得我还以为效果多好呢。。

**Comment by zhengyima** [comment]
据说模型训练集只有10000张图片，效果很好就邪门了 : ) 就娱乐一下吧顺便用用openCV和Pytorch

**Comment by zhengyima** [comment]
> 太假了，网上吹得我还以为效果多好呢。。



> 太假了，网上吹得我还以为效果多好呢。。

据说模型训练集只有10000张图片，效果很好就邪门了 : ) 就娱乐一下吧顺便用用openCV和Pytorch

**Comment by heartInsert** [comment]
> 太假了，网上吹得我还以为效果多好呢。。

媒体总是瞎JB乱吹
