### ISSUE TITLE
Attribute Erro

### ISSUE THREAD

**Issue by 654323** [zhengyima/DeepNude_NoWatermark_withModel#13]
I keep getting this error 

`AttributeError: 'NonneType' object has no attribute "shape"`

Any suggestions?

**Comment by boogiehoogie** [comment]
Make sure the input file is a png file named "input.png" exactly. 

The script expects input.png and when it doesnt find it, you are left with an object that stores no information, the NoneType object. If you are familiar at all with Java it is like a NullPointerException.

**Comment by 654323** [comment]
I can confirm it is "input.png" exactly and that it is a png file type. 
I am supposed to be running the main.py file, correct?

**Comment by zhengyima** [comment]
> I keep getting this error
> 
> `AttributeError: 'NonneType' object has no attribute "shape"`
> 
> Any suggestions?

Check the filename of input or the existence of the input image. i guess the program cannot get the input image , which leads to the` NoneType`. Good Luck : )
