### ISSUE TITLE
这根本不是脱衣服，而是覆盖

### ISSUE THREAD

**Issue by lkt0508** [zhengyima/DeepNude_NoWatermark_withModel#15]
![image](https://user-images.githubusercontent.com/45195898/61115954-37504c80-a4c6-11e9-9c7b-7fd06adec2e1.png)

**Comment by zhengyima** [comment]
人家这模型就只能接受小姐姐你非得输个狗子，这怪谁:)

**Comment by zhengyima** [comment]
您这图容易被和谐，所以一会儿把这个issue删了哈。有其他问题您可以再发个别的issue :)

**Comment by RC1844** [comment]
输出有些图片真是惨不忍睹，奈子长到膝盖上了😱
