### ISSUE TITLE
Script works and creates output, but very bad picture quality

### ISSUE THREAD

**Issue by kaiwaehner** [zhengyima/DeepNude_NoWatermark_withModel#17]
Got it running on my Mac (using CPU option). 

The original image works. The output is worse quality than the input, but still okay.

If I use a custom image, it does not create good output (very bad quality and colors, you almost cannot realize it is a woman). 

What are the requirements to run this model better?
- I downloaded the three models, but did not do any config changes or select a specific model. Which one is best?
- Does the picture require a specific resolution?
- Is it possible to create good outputs at all with this model?

Thanks.

**Comment by zhengyima** [comment]
First, the three model deals with different steps in this project. For example, the cm.lib deals with the correct_to_mask step. You can check it in `run.py`. So i think we can not improve the quality by selecting a model file :(

Secondly, i am not sure. but it seems that every photo inputted in the model will be outputted with lower quality.

Thirdly, I have tried to create good outputs, where i print out all the images outputted by each steps defined in `run.py`. i find that the `dress_to_correct` step, which is also the first step of seven, has already lowed the quality of the photo. If you are interested in improving the quality, i recommend you can check the `run.py` for the seven steps in detail.

I am very happy you are interested in this project and communicate with me. Good luck :) :+1:

**Comment by kaiwaehner** [comment]
Thanks for the detailed explanations.

**Comment by baptx** [comment]
To answer your question about the resolution, I read on another fork (https://github.com/stacklikemind/deepnude_official) that it should be 512x512 pixels:
> The script will transform input.png to output.png. The input.png should be 512pixel*512pixel
Does someone know what should be changed to support larger resolutions and resolutions that don't have the same width and height? I think this issue can be kept open so it is more visible if someone wants to improve the code.
