### ISSUE TITLE
virus included，dont download

### ISSUE THREAD

**Issue by raykingmine** [zhengyima/DeepNude_NoWatermark_withModel#2]

**Comment by zhengyima** [comment]
The source code in my repository is open source, you can check whether there is any danger. I ensure there is no virus and my project can cause no damage to anyone's computer. Maybe there is something wrong with antivirus software :)

**Comment by kindect** [comment]
哇 第一次在Github上看到说代码里有毒的 “挖个坟” ，骂一句 sb吧
