### ISSUE TITLE
Running in docker FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cm.lib'

### ISSUE THREAD

**Issue by maralik** [zhengyima/DeepNude_NoWatermark_withModel#21]
When I run the app in Docker as described, I got:
`
docker run --rm -it -v $PWD:/app:rw ababy/python-deepnude /bin/bash
root@11dcb1effe70:/app# ls
README.md  gan.py  input.png  main.py  opencv_transform  readmeimgs  run.py
root@11dcb1effe70:/app# python main.py
libpng warning: iCCP: known incorrect sRGB profile
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 21, in main
    watermark = process(dress)
  File "/app/run.py", line 115, in process
    model.initialize(opt)
  File "/app/gan.py", line 69, in initialize
    self.__load_network(self.netG)
  File "/app/gan.py", line 89, in __load_network
    network.load_state_dict(torch.load(save_path))
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cm.lib'
root@11dcb1effe70:/app# 
`

How can I fix this?

Thanks

**Comment by RenYuH** [comment]
I got same error like u,u should download it by yourself

**Comment by RenYuH** [comment]
magnet:?xt=urn:btih:7BE4EB8D640742D2FFEBD6495E9392E9E2C399BC

**Comment by zhengyima** [comment]
@fizzday

**Comment by ruichengping** [comment]
you should move three **.lib** file in **pyqtlib** to **checkpoints**

**Comment by xuyafan** [comment]
> you should move three **.lib** file from **checkpoints/pyqtlib** to **checkpoints**

where is .lib file in Docker?

**Comment by zengxiaoliang** [comment]
where is .lib file

**Comment by zengxiaoliang** [comment]
> magnet:?xt=urn:btih:7BE4EB8D640742D2FFEBD6495E9392E9E2C399BC

this is for win? Could U please show me the  lib

**Comment by ruichengping** [comment]
> > you should move three **.lib** file from **checkpoints/pyqtlib** to **checkpoints**
> 
> where is .lib file in Docker?

- Firstly，you should download **.lib** file by the README.md
![image](https://user-images.githubusercontent.com/21974507/61259743-1d588780-a7ae-11e9-8cc8-7549debad987.png)

- Then,you will receive a rar file,unrar this file and move all the unrared  file  into **DeepNude_NoWatermark_withModel/checkpoints**

- Finally,move three .lib file from **checkpoints/pyqtlib** to **checkpoints**.
![image](https://user-images.githubusercontent.com/21974507/61260369-732e2f00-a7b0-11e9-845f-a74aabf71a14.png)

**Comment by ruichengping** [comment]
> please

this is a rar file,but no problem in mac,you can install **Dr.Unarchiver**which can unrar the rar file.
Final Directory:
![image](https://user-images.githubusercontent.com/21974507/61260369-732e2f00-a7b0-11e9-845f-a74aabf71a14.png)

**Comment by zhengyima** [comment]
> > > you should move three **.lib** file from **checkpoints/pyqtlib** to **checkpoints**
> > 
> > 
> > where is .lib file in Docker?
> 
> * Firstly，you should download **.lib** file by the README.md
>   ![image](https://user-images.githubusercontent.com/21974507/61259743-1d588780-a7ae-11e9-8cc8-7549debad987.png)
> * Then,you will receive a rar file,unrar this file and move all the unrared  file  into **DeepNude_NoWatermark_withModel/checkpoints**
> * Finally,move three .lib file from **checkpoints/pyqtlib** to **checkpoints**.
>   ![image](https://user-images.githubusercontent.com/21974507/61260369-732e2f00-a7b0-11e9-845f-a74aabf71a14.png)

:+1:
