### ISSUE TITLE
docker running cause cv error 

### ISSUE THREAD

**Issue by RenYuH** [zhengyima/DeepNude_NoWatermark_withModel#22]
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main2()
  File "main.py", line 17, in main2
    watermark = process(dress)
  File "/app/run.py", line 140, in process
    maskref = create_maskref(mask, correct)
  File "/app/opencv_transform/mask_to_maskref.py", line 37, in create_maskref
    res1 = cv2.bitwise_and(cv_correct, cv_correct, mask = green_mask_inv)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/core/src/arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'

**Comment by zhengyima** [comment]
@fizzday

**Comment by ruichengping** [comment]
you should install opencv-python like `pip install opencv-python`

**Comment by RenYuH** [comment]
@ruichengping 😯
I tried but got this

Requirement already satisfied: opencv-python in /usr/local/lib/python3.7/site-packages (4.1.0.25)
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.7/site-packages (from opencv-python) (1.16.4)
