### ISSUE TITLE
docker运行失败

### ISSUE THREAD

**Issue by lilinxi** [zhengyima/DeepNude_NoWatermark_withModel#24]
Unable to find image 'ababy/python-deepnude:latest' locally

docker: Error response from daemon: Get https://registry-1.docker.io/v2/ababy/python-deepnude/manifests/latest: unauthorized: incorrect username or password.

**Comment by zhengyima** [comment]
@fizzday

**Comment by fizzday** [comment]
> Unable to find image 'ababy/python-deepnude:latest' locally
> 
> docker: Error response from daemon: Get https://registry-1.docker.io/v2/ababy/python-deepnude/manifests/latest: unauthorized: incorrect username or password.

you must use docker official   site
