### ISSUE TITLE
unable to download models

### ISSUE THREAD

**Issue by drwaffle1234** [zhengyima/DeepNude_NoWatermark_withModel#25]
the magnet link is not downloading anything for do you know whats up with that

**Comment by claford-v-lawrence** [comment]
Works for me. Maybe search for some trackers? What's your client?

**Comment by drwaffle1234** [comment]
I'm using Tixtai but I will download a different one now

**Comment by drwaffle1234** [comment]
I download a new client and it worked thanks for giving me that idea
