### ISSUE TITLE
docker 里面没有那三个.lib?

### ISSUE THREAD

**Issue by likuankuan** [zhengyima/DeepNude_NoWatermark_withModel#26]
没有那三个.lib怎么会这么大？

**Comment by wshelly** [comment]
这三个.lib怎么下载

**Comment by likuankuan** [comment]
用百度网盘可以下载

**Comment by ruichengping** [comment]
> 这三个.lib怎么下载
Readme.md上说的很清楚
![image](https://user-images.githubusercontent.com/21974507/61424043-c0dba080-a944-11e9-92f3-e9ca04a62769.png)
下载完成之后解压，三个.lib文件在**pyqtlib**这个文件夹下

**Comment by zhengyima** [comment]
在readme中更新了一个链接，目前是可用的。
