### ISSUE TITLE
Which version of opencv will be correct?

### ISSUE THREAD

**Issue by graycrown** [zhengyima/DeepNude_NoWatermark_withModel#3]
File "main.py", line 45, in <module>
    main2()
  File "main.py", line 17, in main2
    watermark = process(dress)
  File "/home/mingming/Desktop/DeepNude_NoWatermark_withModel-master/run.py", line 144, in process
    maskfin = create_maskfin(maskref, maskdet)
  File "/home/mingming/Desktop/DeepNude_NoWatermark_withModel-master/opencv_transform/maskdet_to_maskfin.py", line 34, in create_maskfin
    bodypart_list = extractAnnotations(maskdet);
  File "/home/mingming/Desktop/DeepNude_NoWatermark_withModel-master/opencv_transform/maskdet_to_maskfin.py", line 101, in extractAnnotations
    tits_list = findBodyPart(maskdet, "tit")
  File "/home/mingming/Desktop/DeepNude_NoWatermark_withModel-master/opencv_transform/maskdet_to_maskfin.py", line 168, in findBodyPart
    contours, hierarchy = cv2.findContours(color_mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)

**Comment by zhengyima** [comment]
> File "main.py", line 45, in 
> main2()
> File "main.py", line 17, in main2
> watermark = process(dress)
> File "/home/mingming/Desktop/DeepNude_NoWatermark_withModel-master/run.py", line 144, in process
> maskfin = create_maskfin(maskref, maskdet)
> File "/home/mingming/Desktop/DeepNude_NoWatermark_withModel-master/opencv_transform/maskdet_to_maskfin.py", line 34, in create_maskfin
> bodypart_list = extractAnnotations(maskdet);
> File "/home/mingming/Desktop/DeepNude_NoWatermark_withModel-master/opencv_transform/maskdet_to_maskfin.py", line 101, in extractAnnotations
> tits_list = findBodyPart(maskdet, "tit")
> File "/home/mingming/Desktop/DeepNude_NoWatermark_withModel-master/opencv_transform/maskdet_to_maskfin.py", line 168, in findBodyPart
> contours, hierarchy = cv2.findContours(color_mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
> ValueError: too many values to unpack (expected 2)

I use 4.1.0.25. Maybe you can try installing the environment with Anaconda, just as what i said in the readme.md :)

**Comment by suwey** [comment]
I use same version and no problem running main.py

**Comment by liuhangfan** [comment]
if you are stuck in this error, try 
contours, hierarchy = cv2.findContours(color_mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
to
_, contours, hierarchy = cv2.findContours(color_mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

**Comment by chouchouzzj** [comment]
pip install opencv-python==4.1.0.25
