### ISSUE TITLE
from run import process失败是我版本不对吗

### ISSUE THREAD

**Issue by jiusazai** [zhengyima/DeepNude_NoWatermark_withModel#30]
![捕获](https://user-images.githubusercontent.com/20239615/61650480-66e12f00-ace6-11e9-8483-76f07d31cbab.PNG)
![捕获2](https://user-images.githubusercontent.com/20239615/61650481-6779c580-ace6-11e9-9693-6f752a39fdc7.PNG)

**Comment by D-Walter** [comment]
请安装版本适配的PyTorch和TorchVision

**Comment by zhengyima** [comment]
如上
