### ISSUE TITLE
老大，GPU要如何安装配置才能用哈？总是提示找不到

### ISSUE THREAD

**Issue by Beckett8888** [zhengyima/DeepNude_NoWatermark_withModel#43]
![image](https://user-images.githubusercontent.com/57650267/69603878-d2e9f000-1056-11ea-8b21-df7ead3dbf8e.png)
![image](https://user-images.githubusercontent.com/57650267/69603902-df6e4880-1056-11ea-993d-2e8cd71060c9.png)

**Comment by zhengyima** [comment]
这是自己配置的问题，我这边搞定不了= =不行就用cpu吧
