### ISSUE TITLE
磁力链接失效？

### ISSUE THREAD

**Issue by ShawnNew** [zhengyima/DeepNude_NoWatermark_withModel#47]
你好，我尝试使用磁力链接下载模型，但是一直没有下载速度。请问是不是磁力链接失效？

**Comment by zhengyima** [comment]
应该是失效了吧。baidupan也不让分享。

我今明两天会再提供一个新的Google Drive链接。

**Comment by ShawnNew** [comment]
> 应该是失效了吧。baidupan也不让分享。
> 
> 我今明两天会再提供一个新的Google Drive链接。

我这任务比较紧，能甩一个google drive的链接吗？

**Comment by Crazyjoedevola** [comment]
Can anyone please provide a valid link?

**Comment by zhengyima** [comment]
new link: [dn.zip](http://39.105.149.229/dn.zip)
unzip this file and you will get the three checkpoint files

i am also going to provide a google drive link soon.
@Crazyjoedevola @ShawnNew

**Comment by zhengyima** [comment]
https://drive.google.com/drive/folders/1OKuIp0nxMUucgEScTc2vESvlpKzIWav4?usp=sharing
