### ISSUE TITLE
运行示例的png图片没问题, 运行自己下载的jpg图片, 就报这个错误

### ISSUE THREAD

**Issue by fizzday** [zhengyima/DeepNude_NoWatermark_withModel#5]
root@687e7442775c:/app# python main.py 
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Executing phase: mask_to_maskref
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main()
  File "main.py", line 22, in main
    watermark = process(dress)
  File "/app/run.py", line 140, in process
    maskref = create_maskref(mask, correct)
  File "/app/opencv_transform/mask_to_maskref.py", line 38, in create_maskref
    res2 = cv2.bitwise_and(green, green, mask = green_mask)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/core/src/arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'

**Comment by zhengyima** [comment]
> root@687e7442775c:/app# python main.py
> Executing phase: dress_to_correct
> Executing phase: correct_to_mask
> Executing phase: mask_to_maskref
> Traceback (most recent call last):
> File "main.py", line 31, in 
> main()
> File "main.py", line 22, in main
> watermark = process(dress)
> File "/app/run.py", line 140, in process
> maskref = create_maskref(mask, correct)
> File "/app/opencv_transform/mask_to_maskref.py", line 38, in create_maskref
> res2 = cv2.bitwise_and(green, green, mask = green_mask)
> cv2.error: OpenCV(4.1.0) /io/opencv/modules/core/src/arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'

Windows的话用画图调整一下大小，调成像素512x512的 :) 

感谢提醒，我在readme.md里注明一下。

**Comment by fizzday** [comment]
> > root@687e7442775c:/app# python main.py
> > Executing phase: dress_to_correct
> > Executing phase: correct_to_mask
> > Executing phase: mask_to_maskref
> > Traceback (most recent call last):
> > File "main.py", line 31, in
> > main()
> > File "main.py", line 22, in main
> > watermark = process(dress)
> > File "/app/run.py", line 140, in process
> > maskref = create_maskref(mask, correct)
> > File "/app/opencv_transform/mask_to_maskref.py", line 38, in create_maskref
> > res2 = cv2.bitwise_and(green, green, mask = green_mask)
> > cv2.error: OpenCV(4.1.0) /io/opencv/modules/core/src/arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'
> 
> Windows的话用画图调整一下大小，调成像素512x512的 :)
> 
> 感谢提醒，我在readme.md里注明一下。

我用的docker, python:latest 安装的所有依赖,  待会儿把他push到docker hub, 共享出来, 就不用折腾环境了, 一键运行

**Comment by zhengyima** [comment]
> > > root@687e7442775c:/app# python main.py
> > > Executing phase: dress_to_correct
> > > Executing phase: correct_to_mask
> > > Executing phase: mask_to_maskref
> > > Traceback (most recent call last):
> > > File "main.py", line 31, in
> > > main()
> > > File "main.py", line 22, in main
> > > watermark = process(dress)
> > > File "/app/run.py", line 140, in process
> > > maskref = create_maskref(mask, correct)
> > > File "/app/opencv_transform/mask_to_maskref.py", line 38, in create_maskref
> > > res2 = cv2.bitwise_and(green, green, mask = green_mask)
> > > cv2.error: OpenCV(4.1.0) /io/opencv/modules/core/src/arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'
> > 
> > 
> > Windows的话用画图调整一下大小，调成像素512x512的 :)
> > 感谢提醒，我在readme.md里注明一下。
> 
> 我用的docker, python:latest 安装的所有依赖, 待会儿把他push到docker hub, 共享出来, 就不用折腾环境了, 一键运行

好呀，非常欢迎 : )

**Comment by fizzday** [comment]
已提交pr

**Comment by zhengyima** [comment]
尺寸问题已修复，运行前已无需调整尺寸，程序输出图片也与输入保持一致：）

**Comment by smoryan** [comment]
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    main(inputpath, outputpath)
  File "main.py", line 20, in main
    h = dress.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
这是因为什么，我用jpg格式的，大小601K

**Comment by 6D1996** [comment]
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:62] data. DefaultCPUAllocator: not enough memory: you tried to allocate %dGB. Buy new RAM!3
这是说我电脑跑不动的呗

**Comment by lord19871207** [comment]
尺寸问题仍然存在啊，我在mac 上运行 只有转成512x512 才能运行

**Comment by Vencenter** [comment]
h = dress.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by MX-Qulin** [comment]
报错？？
Processing input.png
libpng warning: iCCP: known incorrect sRGB profile
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "main.py", line 35, in main
    watermark = deep_nude_process(inputpath)
  File "main.py", line 46, in deep_nude_process
    watermark = process(dress)
  File "/app/run.py", line 115, in process
    model.initialize(opt)
  File "/app/gan.py", line 68, in initialize
    opt.n_blocks_local, opt.norm, self.gpu_ids)        
  File "/app/gan.py", line 117, in __define_G
    netG.cuda(gpu_ids[0])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
