### ISSUE TITLE
试了下 效果不怎么样 比基尼的还可以 普通衣服的非常糟糕

### ISSUE THREAD

**Issue by lzx52154314** [zhengyima/DeepNude_NoWatermark_withModel#53]

**Comment by DerStilleStaub** [comment]
![c75c10385343fbf2c7c6b1567dd9358464388f0d](https://user-images.githubusercontent.com/34789232/104231859-81830700-548a-11eb-90b5-982fb25fcab6.jpeg)

**Comment by zhengyima** [comment]
是的 这个模型的能力的确有限
