### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by Dipsome** [zhengyima/DeepNude_NoWatermark_withModel#57]
HOW CAN I Do

line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by AlexanderProd** [comment]
you need to install opencv 

`python3 -m pip install opencv-python`

**Comment by baptx** [comment]
This could be added in the README.

**Comment by dvdcjw** [comment]
Looks like the term "nude" really brought many people even ones who don't know how to use python
